### ISSUE TITLE
Update launcher UI and functionality for PSForever only servers

### ISSUE THREAD

**Issue by pschord** [psforever/GameLauncher#2]
PlanetSide 1 is gone.

We want a way to point to our own local or remote servers. We want an automatic way to rewrite the `client.ini` in the planetside folder so people don't have any issues getting up and running.

We need a way to get the server IP and port.
This could be done through a settings page for now. Note, only skip launcher would be available as the username and password requires a webserver.

A potential matchmaking server would be great to have in the future.

**Comment by psmook** [comment]
Shortlist: 
- Create a small footprint GUI that is pre-populated with a **hostname**. Querying this hostname would result in an XML manifest file that would list all _officially supported_ PSForever Servers. 
- Implement a "Custom" option, that allows you to enter in _unofficially supported_ **hostname** XML manifest file. 
- Depending upon the user's choice, the XML manifest file would be challenged against the `client.ini` and if the IP addresses do not match, it would automatically update the `client.ini` (while preserving a backup of the most recent changes.) 
- Once complete, the launchpad would then perform checksum's on all client files against the manifest server IP addresses. 
- If a mismatch occurs, the client would not be allowed to login and would be presented with the option to upgrade. **Upgrades should not be automatic, allowing for people to hop server types!**
- Assuming everything is good, the option to launch the game client would appear. The server would also perform similar checks. 

Does that sound about right? 

I could probably write this in visual basic, but it has... been a while.

**Comment by pschord** [comment]
The latest release version of 1.2.0.0 now supports client.ini rewriting and server adding/selection. No file updating as this will be superseded by another launcher (hopefully).
